<a href="https://colab.research.google.com/github/wendyxie6/python-learning-journal/blob/main/NumPy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Exercises**

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong>
Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

1. Import NumPy using the alias `np`

In [ ]:
import numpy as np

2. Create an array of 15 zeros

In [ ]:
myArray = np.zeros(15)
myArray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create an array of 5 sevens

In [ ]:
myArray = np.zeros(5)
myArray[:] = 7
myArray

array([7., 7., 7., 7., 7.])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([7., 7., 7., 7., 7.])

4. Create a NumPy array from the Python list `[2, 4, 6, 8, 10]`

In [ ]:
myArray = np.arange(2, 11, 2)
myArray

array([ 2,  4,  6,  8, 10])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([ 2,  4,  6,  8, 10])

5. Create an array of the integers from 50 to 100

In [ ]:
myArray = np.arange(50, 101)
myArray

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

 6. Create an array of all the even integers from 50 to 100

In [ ]:
myArray = np.arange(50, 101, 2)
myArray

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

 7. Create an array of all the odd integers from 50 to 100

In [ ]:
myArray = np.arange(51, 100,2)
myArray

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

8. Create a 3x4 matrix with values ranging from 1 to 12

In [ ]:
myArray = np.arange(1,13).reshape(3,4)
myArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

9. Create a 2×4 array of all ones

In [ ]:
myArray = np.ones(8).reshape(2, 4)
myArray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

10. Generate a random number between 0 and 1
**NOTE:** Your result's value should be different from the one shown below.

In [ ]:
myArray = np.random.rand(1)
myArray

array([0.93937562])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([0.99227295])

11. Generate an array of 15 random numbers sampled from a standard normal distribution

**NOTE:** Your result's values should be different from the ones shown below.

In [ ]:
myArray = np.random.randn(15)
myArray

array([-0.06242445, -0.36147762,  0.9388052 ,  0.36061287, -1.69995107,
       -0.06209956, -0.4156662 , -0.05689664,  0.86672228, -0.04458029,
        1.09792365,  0.75808063,  0.19172391,  0.23710402,  0.20001769])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([ 0.21934806,  0.17760888, -0.91184506,  0.2133419 ,  1.26897388,
       -1.28591711, -1.04358125, -1.33452188, -0.2024905 ,  0.01961711,
        1.49796155, -1.20897545, -0.17358371, -1.88379736,  0.25949144,
        0.44617008, -0.64195543, -0.64400601,  0.6557413 ,  0.56882346,
        1.11558617, -0.75943237, -0.71048492,  1.67016631,  0.58620761])

12. Create the following matrix:

In [ ]:
myArray = np.arange(0.1, 5.1, 0.1).reshape(5, 10)
myArray

array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ],
       [3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. ],
       [4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ]])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ],
       [3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. ],
       [4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ]])

13. Create an array of 10 linearly spaced points between 0 and 2:

In [ ]:
tmpArray = np.linspace(0, 2, 10)
tmpArray

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

## **Numpy Indexing and Selection**

Now you will be given a starting matrix, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

14. Write code that reproduces the output shown below.<br><br>&emsp;&ensp;Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.

In [ ]:
tmpArray = np.arange(12, 26)
tmpArray = np.delete(tmpArray, 4)
myArray = np.delete(tmpArray, 8).reshape(3,4)
myArray

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

15. Write code that reproduces the output shown below.

In [ ]:
myArray = np.arange(10,21)
myArray[10]

np.int64(20)

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

np.int64(20)

16. Write code that reproduces the output shown below.

In [ ]:
myArray = np.arange(2,5).reshape(3,1)
myArray[1] = myArray[0] + 5
myArray[2] = myArray[1] + 5
myArray

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([[ 2],
       [ 7],
       [12]])

17. Write code that reproduces the output shown below.

In [ ]:
myArray = np.arange(21, 26)
myArray

array([21, 22, 23, 24, 25])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([21, 22, 23, 24, 25])

18. Write code that reproduces the output shown below.

In [ ]:
myArray = np.arange(16, 26).reshape(2,5)
myArray

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

## **NumPy Operations**

19. Get the sum of all the values in matrix or 2D array you've working with

In [ ]:
total = np.sum(myArray)
total

np.int64(205)

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

np.int64(325)

20. Get the standard deviation of the values in mat

In [ ]:
div = total/3
div

np.float64(68.33333333333333)

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

np.float64(7.211102550927978)

21. Get the sum of all the columns in mat

In [ ]:
column_sum = sum(myArray)
column_sum

array([37, 39, 41, 43, 45])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([55, 60, 65, 70, 75])

22. Given:

In [ ]:
arr = np.array([3, 7, 12, 18, 25, 30])

Extract all elements greater than 10.

In [ ]:
myArray = np.array([3, 7, 12, 18, 25, 30])
newArray = myArray[myArray>10]
newArray


array([12, 18, 25, 30])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([12, 18, 25, 30])

23. Given:





In [ ]:
arr = np.array([5, 12, 7, 20, 3, 15])
arr

array([ 5, 12,  7, 20,  3, 15])

Replace all elements greater than 10 with 99.

In [ ]:
myArray = np.array([5, 12, 7, 20, 3, 15])
myArray[myArray>10] = 99
myArray

array([ 5, 99,  7, 99,  3, 99])

In [ ]:
# DON'T WRITE HERE, DON'T RUN THIS CELL

array([ 5, 99,  7, 99,  3, 99])